language: r
sudo: required
warnings_are_errors: true
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/424a6466ffc9230077b0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
